import {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createPortal} from 'react-dom';
import {motion,MotionConfig,useReducedMotion} from 'motion/react';
import {LayoutDashboard,Users,Wallet,Sun,History,ArrowUpRight,ArrowRight,ChevronLeft,ChevronRight,Download,Check,Plus,Search,Menu,X,HelpCircle,GraduationCap,RefreshCw,Landmark,Sparkles,ChartNoAxesCombined,CloudDownload,Receipt,Info} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from './components/ui/tabs';
import {NumberTicker} from './components/magicui/number-ticker';
import '@fontsource-variable/manrope';
import '@fontsource-variable/geologica';
import './legacy.css';
import './style.css';
import {prepareLegacy,expandTeacher} from './bridge';
prepareLegacy();
const $=id=>document.getElementById(id);
const money=n=>Math.round(n).toLocaleString('ru-RU')+' ₽';
const ids=['totalRevenue','totalPupils','totalFot','totalHandsPay','totalDeposit','depositYearly','adminPay','adminNote','adminGap','totalAllPay','totalAllSub','totalRemainder','remainderSub','reserveAmt','reserveSub','summerMonthlyCard','summerCardSub','freeAmt','freeSub','potentialRevenue','potentialDiff','paidReal','paidSub','paidSplit','paidWays','debtReal','debtSub','spentReal','spentSub','monthLabel','monthNote','fixedTotal','taxVal','costVal','cashLeft','cashLeftSub'];
function snapshot(){return Object.fromEntries(ids.map(id=>[id,$(id)?.textContent||'']))}
const numeric=v=>Number(String(v).replace(/[^\d−-]/g,'').replace('−','-'))||0;
const nav=[['overview','Обзор месяца',LayoutDashboard],['teachers','Зарплаты педагогов',Users],['admin','Администратор',Users],['payments','Фиксированные выплаты',Wallet],['reserves','Кредиты и резервы',Landmark],['premium','Годовая премия',Sparkles]];
function App(){
 const [data,setData]=useState(snapshot); const [view,setView]=useState(()=>{const selected=new URLSearchParams(window.location.search).get('view');return nav.some(([id])=>id===selected)?selected:'overview'}); const [menu,setMenu]=useState(false); const [saved,setSaved]=useState(false); const [help,setHelp]=useState(false); const [query,setQuery]=useState(''); const [teacher,setTeacher]=useState('all'); const [capacity,setCapacity]=useState(0); const [hover,setHover]=useState(-1); const reduced=useReducedMotion();
 useEffect(()=>{let frame;const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>setData(snapshot()))};const observer=new MutationObserver(update);observer.observe(document.querySelector('.summary-grid'),{subtree:true,childList:true,characterData:true});observer.observe($('monthLabel'),{childList:true});observer.observe($('monthNote'),{childList:true});return()=>{observer.disconnect();cancelAnimationFrame(frame)}},[]);
 useEffect(()=>{document.body.dataset.view=view;if(view==='admin'){const block=$('fixed-payments');block.dataset.collapsed='false';block.querySelector('.finance-toggle')?.setAttribute('aria-expanded','true')}},[view]);
 useEffect(()=>{const media=window.matchMedia('(max-width:1000px)');const sync=()=>{document.querySelector('.sidebar').inert=media.matches&&!menu};sync();media.addEventListener('change',sync);return()=>media.removeEventListener('change',sync)},[menu]);
 useEffect(()=>{const filter=()=>document.querySelectorAll('.teacher-block').forEach((el,i)=>{el.hidden=(teacher!=='all'&&String(i)!==teacher)||!el.textContent.toLowerCase().includes(query.toLowerCase())});filter();const obs=new MutationObserver(filter);obs.observe($('teachersContainer'),{childList:true});return()=>obs.disconnect()},[teacher,query]);
 useEffect(()=>{if(!help)return;const dialog=$('help-dialog');dialog.showModal();return()=>dialog.close()},[help]);
 const go=v=>{setView(v);setMenu(false);const url=new URL(window.location.href);url.searchParams.set('view',v);url.hash='';window.history.replaceState(null,'',url);window.scrollTo({top:0,behavior:'instant'})};
 useEffect(()=>{if(!menu)return;const sidebar=document.querySelector('.sidebar');const trigger=document.querySelector('.mobile-menu');sidebar.querySelector('.mobile-close')?.focus();const handle=e=>{if(e.key==='Escape'){setMenu(false);trigger?.focus()}if(e.key==='Tab'){const nodes=[...sidebar.querySelectorAll('a,button')].filter(el=>el.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',handle);return()=>document.removeEventListener('keydown',handle)},[menu]);
 const month=$('monthPicker').value;
 const changeMonth=v=>{if(!/^\d{4}-\d{2}$/.test(v))return;const picker=$('monthPicker');picker.value=v;picker.dispatchEvent(new Event('change',{bubbles:true}));setData(snapshot());setCapacity(0)};
 const shiftMonth=step=>{const [y,m]=month.split('-').map(Number);const d=new Date(y,m-1+step,1);changeMonth(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`)};
 const save=()=>{window.saveMonth();setSaved(true);setTimeout(()=>setSaved(false),2400)};
 const revenue=numeric(data.totalRevenue),potential=numeric(data.potentialRevenue),fot=numeric(data.totalFot),deposit=numeric(data.totalDeposit);
 const segments=[{label:'Педагоги',value:fot,color:'#7952cc'},{label:'Фиксированные выплаты',value:Math.max(0,numeric(data.totalAllPay)-fot),color:'#c2afe8'},{label:'Прибыль после выплат',value:Math.max(0,revenue-numeric(data.totalAllPay)),color:'#efc95b'}];
 const shown=hover<0?{label:'Начисленная выручка',value:revenue}:segments[hover];
 const angle=segments.map(x=>revenue?x.value/revenue*100:0);let start=0;const gradient=segments.map((s,i)=>{const from=start;start+=angle[i];return `${s.color} ${from}% ${start}%`}).join(',');
 return <MotionConfig reducedMotion="user"><aside className={`sidebar ${menu?'is-open':''}`} aria-label="Навигация"><a className="brand" href="./" aria-label="Speak and Smile — главная"><span className="brand-mark">s<span>&</span>s<i/></span><span>Speak<span className="brand-amp">&</span>Smile<small>ФИНАНСЫ ШКОЛЫ</small></span></a><button className="mobile-close icon-btn" onClick={()=>setMenu(false)} aria-label="Закрыть меню"><X size={20}/></button><div className="workspace-label"><span className="school-icon"><GraduationCap size={19}/></span><div>Моя школа<small>Рабочее пространство</small></div><span className="live-dot"/></div><p className="nav-caption">УПРАВЛЕНИЕ</p><nav>{nav.map(([id,label,Icon])=><button key={id} onClick={()=>go(id)} aria-current={view===id?'page':undefined} className={`nav-item ${view===id?'active':''}`}><Icon size={18}/>{label}{view===id&&<span className="nav-dot"/>}</button>)}<button className="nav-item" onClick={()=>{setMenu(false);window.openHistoryModal()}}><History size={18}/>История расчётов</button></nav><p className="nav-caption second-caption">УЧЕНИКИ</p><nav><a className="nav-item" href="newcomers.html"><Plus size={18}/>Новенькие<ArrowUpRight size={14}/></a><a className="nav-item" href="otrabotki.html"><RefreshCw size={18}/>Отработки<ArrowUpRight size={14}/></a></nav><div className="sidebar-bottom"><div className="sidebar-note"><span className="tiny-star">✳</span><p>Всё сходится.<br/><strong>Можно выдохнуть.</strong></p><span className="note-line"/></div><button className="nav-item" onClick={()=>{setMenu(false);setHelp(true)}}><HelpCircle size={18}/>Как устроен расчёт</button><div className="profile"><span className="avatar">ОС</span><div>Оксана Синцова<small>Руководитель школы</small></div></div></div></aside>{menu&&<button className="menu-scrim" aria-label="Закрыть меню" onClick={()=>setMenu(false)}/>}
 <div className="app-main"><header className="topbar"><div className="breadcrumb"><button className="icon-btn mobile-menu" onClick={()=>setMenu(true)} aria-label="Открыть меню"><Menu size={20}/></button><span>Рабочее пространство</span><ChevronRight size={14}/><strong>Финансы</strong></div><div className="topbar-right"><span className="local-tag"><i/>Локальный кабинет</span><span className="avatar small">ОС</span></div></header>
 <main id="main" className="dashboard"><div className="page-intro"><div><div className="eyebrow">SPEAK&SMILE / ФИНАНСЫ</div><h1>{view==='overview'?'Вся картина месяца.':nav.find(n=>n[0]===view)?.[1]}</h1><p>{view==='overview'?'От выручки до выплат — всё на своих местах.':'Детали расчёта и настройки выбранного месяца.'}</p></div><div className="period"><button className="icon-btn" aria-label="Предыдущий месяц" onClick={()=>shiftMonth(-1)}><ChevronLeft size={17}/></button><label className="period-label"><span>{data.monthLabel}</span><input aria-label="Расчётный месяц" type="month" value={month} onChange={e=>changeMonth(e.target.value)}/></label><button className="icon-btn" aria-label="Следующий месяц" onClick={()=>shiftMonth(1)}><ChevronRight size={17}/></button></div></div>
 <div className="actionbar"><div className="section-switch"><button className={view==='overview'?'selected':''} onClick={()=>go('overview')}>Обзор</button><button onClick={()=>window.openAnalysis()}>Аналитика<ArrowUpRight size={13}/></button></div><div className="actions"><button className="btn secondary" onClick={()=>window.openBigBenModal()}><CloudDownload size={16}/>Из BigBen</button><button className="btn secondary" onClick={()=>$('csvInput').click()}><Download size={16}/><span>Импорт оплат</span></button><button className="btn primary" onClick={save}>{saved?<Check size={16}/>:<Plus size={16}/>}<span>{saved?'Сохранено':'Сохранить месяц'}</span></button></div></div>
 <nav className="student-shortcuts" aria-label="Ученики"><a href="newcomers.html"><Plus size={16}/>Новенькие<ArrowUpRight size={14}/></a><a href="otrabotki.html"><RefreshCw size={16}/>Отработки<ArrowUpRight size={14}/></a></nav>
 {view==='admin'&&<section className="admin-explanation panel"><h2>Расчёт зарплаты администратора</h2><p>{data.adminNote}</p><p>{data.adminGap}</p></section>}
 {data.monthNote&&<p className="month-note" role="status">{data.monthNote}</p>}
 {view==='overview'&&<motion.div initial={reduced?false:{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{duration:.45}}><section className="headline-grid" aria-label="Показатели месяца"><article className="revenue-card"><div className="revenue-top"><span><i/>Выручка школы</span><span className="pill">{data.totalPupils.includes('прогноз')?'Прогноз по тарифу':'Начислено'}</span></div><div className="hero-number"><NumberTicker value={revenue}/><span>₽</span></div><p className="revenue-sub">{data.totalPupils.split(' · ⚠️')[0]}</p><div className="revenue-divider"/><div className="revenue-bottom"><span>Потенциал при полном наборе<strong>{money(potential)}</strong></span><button className="circle-link" aria-label="Посмотреть потенциал набора" onClick={()=>$('growth').scrollIntoView({behavior:reduced?'instant':'smooth'})}><ArrowUpRight size={23}/></button></div><svg className="revenue-art" viewBox="0 0 260 230" fill="none" aria-hidden="true"><path d="M25 212C25 76 212 232 212 78C212 1 111 5 111 66C111 128 250 108 250 3"/><path d="M5 230C5 96 192 250 192 96C192 19 91 23 91 84C91 146 230 126 230 21"/></svg></article><article className="kpi-card"><div className="kpi-title"><span className="kpi-icon lavender"><Users size={19}/></span><ArrowUpRight size={17}/></div><p>Фонд оплаты педагогов</p><h2><NumberTicker value={fot}/><span> ₽</span></h2><div className="card-rule"/><div className="kpi-foot"><span>25% от выручки</span><span className="mini-pill">ФОТ</span></div><small>{data.totalHandsPay}</small></article><article className="kpi-card"><div className="kpi-title"><span className="kpi-icon honey"><Wallet size={19}/></span><ArrowUpRight size={17}/></div><p>Свободно на руки</p><h2><NumberTicker value={numeric(data.freeAmt)}/><span> ₽</span></h2><div className="card-rule"/><div className="kpi-foot"><span>После обязательств</span><span className="mini-pill warm">ОСТАТОК</span></div><small>{data.freeSub}</small></article></section>
 <section className="fact-strip" aria-label="Фактические оплаты"><div className="fact-item"><span className="status-icon green"><Check size={15}/></span><div><span>Оплачено за месяц</span><strong>{data.paidReal}</strong>{data.paidSplit&&<em className="fact-sub">{data.paidSplit}</em>}{data.paidWays&&<em className="fact-sub">{data.paidWays}</em>}</div></div><div className="fact-item"><span className="status-icon orange"><Receipt size={15}/></span><div><span>Долг за месяц</span><strong>{data.debtReal}</strong>{data.debtSub&&<em className="fact-sub">{data.debtSub}</em>}</div></div><div className="fact-item"><span className="status-icon muted"><Wallet size={15}/></span><div><span>Расходы по CRM</span><strong>{data.spentReal}</strong></div></div><div className="fact-item"><span className="status-icon green"><Wallet size={15}/></span><div><span>Можно взять (по кассе)</span><strong>{data.cashLeft||'—'}</strong>{data.cashLeftSub&&<em className="fact-sub">{data.cashLeftSub}</em>}</div></div><div className="fact-note"><Info size={15}/><span>{data.paidReal==='—'?'Для фактических сумм загрузите оплаты из CRM.':'Фактические суммы из CRM. Подробности ниже.'}</span></div></section>
 <section className="insight-grid"><article className="distribution panel"><div className="panel-head"><div><div className="eyebrow">СТРУКТУРА МЕСЯЦА</div><h2>Куда идут деньги</h2></div><button className="icon-btn" aria-label="Открыть все выплаты" onClick={()=>go('payments')}><ArrowUpRight size={20}/></button></div><div className="distribution-body"><div className="donut" style={{background:revenue?`conic-gradient(${gradient})`:'#ece8f2'}}><div className="donut-hole"><span>{hover<0?'ВЫРУЧКА':shown.label.toUpperCase()}</span><strong>{hover<0?'100':Math.round(shown.value/Math.max(revenue,1)*100)}<small>%</small></strong><span>{money(shown.value)}</span></div></div><div className="legend">{segments.map((s,i)=><button key={s.label} onMouseEnter={()=>setHover(i)} onMouseLeave={()=>setHover(-1)} onFocus={()=>setHover(i)} onBlur={()=>setHover(-1)} className={hover===i?'focused':''}><i style={{background:s.color}}/><span>{s.label}<strong>{money(s.value)}</strong></span><span className="legend-percent">{Math.round(angle[i])}%</span></button>)}<p>Доли от начисленной выручки</p></div></div></article><article className="growth panel" id="growth"><div className="panel-head"><div><div className="eyebrow">ТОЧКА РОСТА</div><h2>Место для большего</h2></div><span className="growth-icon"><ChartNoAxesCombined size={22}/></span></div><div className="growth-number">+<NumberTicker value={Math.max(0,potential-revenue)}/><span> ₽ / мес</span></div><p>Потенциал выручки при наборе до 12 учеников в группу.</p><label className="range-label" htmlFor="capacity">Примерьте полный набор<span>{capacity}% потенциала</span></label><input id="capacity" className="capacity" type="range" min="0" max="100" step="5" value={capacity} onChange={e=>setCapacity(+e.target.value)} style={{'--fill':`${capacity}%`}}/><div className="range-result"><span>{capacity===0?'Текущая выручка':'Сценарий выручки'}</span><strong>{money(revenue+(Math.max(0,potential-revenue)*capacity/100))}</strong></div><small>Сценарий не изменяет расчёт зарплат.</small></article></section>
 <section className="detail-metrics"><div><Users size={18}/><span>Администратор<strong>{data.adminPay}</strong></span><button className="icon-btn" aria-label="Открыть администратора" onClick={()=>go('admin')}><ArrowUpRight size={16}/></button></div><div><Wallet size={18}/><span>Фиксированные выплаты<strong>{data.fixedTotal}</strong></span><button className="icon-btn" aria-label="Открыть фиксированные выплаты" onClick={()=>go('payments')}><ArrowUpRight size={16}/></button></div><div><Receipt size={18}/><span>Прочие расходы и налоги<strong>{money(numeric(data.costVal)+numeric(data.taxVal))}</strong></span><button className="icon-btn" aria-label="Открыть расходы и налоги" onClick={()=>go('payments')}><ArrowUpRight size={16}/></button></div><div><Sun size={18}/><span>Фонд лета<strong>{data.summerMonthlyCard}</strong></span><button className="icon-btn" aria-label="Настроить фонд лета" onClick={()=>go('reserves')}><ArrowUpRight size={16}/></button></div><div><Landmark size={18}/><span>Кредиты в месяц<strong>{data.reserveAmt}</strong></span><button className="icon-btn" aria-label="Открыть кредиты" onClick={()=>go('reserves')}><ArrowUpRight size={16}/></button></div><div><GraduationCap size={18}/><span>Отпускные педагогов<strong>{money(deposit)}</strong></span><button className="icon-btn" aria-label="Открыть отпускные" onClick={()=>go('reserves')}><ArrowUpRight size={16}/></button></div></section></motion.div>}
 </main></div>
 {createPortal(<div className="teacher-toolbar"><div className="teacher-title"><div><div className="eyebrow">КОМАНДА ШКОЛЫ</div><h2>Зарплаты педагогов <span>3</span></h2></div><label className="search-field"><Search size={16}/><input placeholder="Найти педагога или группу" aria-label="Поиск по педагогам и группам" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><Tabs value={teacher} onValueChange={value=>{setTeacher(value);expandTeacher(value==='all'?null:value)}}><TabsList aria-label="Выбор педагога"><TabsTrigger value="all">Все педагоги</TabsTrigger><TabsTrigger value="0">Екатерина</TabsTrigger><TabsTrigger value="1">Ксения</TabsTrigger><TabsTrigger value="2">Оксана</TabsTrigger></TabsList>{['all','0','1','2'].map(x=><TabsContent value={x} key={x}><p className="table-hint">Нажмите на имя, чтобы раскрыть расчёт по группам. 25% от выручки · отпускные отдельно.</p></TabsContent>)}</Tabs></div>,$('teacher-toolbar'))}
 {createPortal(<footer className="app-footer"><span>Speak&Smile <span className="footer-dot">·</span> Финансы школы</span><button onClick={()=>{setMenu(false);setHelp(true)}}>Как считается зарплата <ArrowUpRight size={13}/></button></footer>,document.getElementById('footer-root'))}
 <div className="save-toast" role="status">{saved&&<><Check size={16}/>Расчёт за {data.monthLabel} сохранён</>}</div>
 <dialog id="help-dialog" className="help-dialog" onClose={()=>setHelp(false)} onClick={e=>{if(e.target===e.currentTarget)setHelp(false)}}><button className="icon-btn dialog-close" aria-label="Закрыть справку" onClick={()=>setHelp(false)}><X size={20}/></button><div className="eyebrow">ПРОЗРАЧНЫЙ РАСЧЁТ</div><h2>Как всё считается</h2><p>Действующие правила из исходного калькулятора Speak&Smile.</p><dl><dt>Педагоги</dt><dd>25% от выручки группы. Депозит на отпускные и сумма на руки показаны отдельно в каждой группе.</dd><dt>Администратор</dt><dd>5% от выручки с возвращёнными скидками абонементов, но не ниже установленного минимума.</dd><dt>Отработки</dt><dd>25 ₽ за минуту фактического урока.</dd><dt>Прогноз и факт</dt><dd>Без начислений CRM отображается прогноз по тарифу. Пустая сумма оплат означает отсутствие данных, а не нулевую оплату.</dd><dt>Сохранение</dt><dd>Расчёты и история сохраняются в этом браузере. Данные с опубликованного сайта не переносятся автоматически.</dd></dl><button className="btn primary" onClick={()=>setHelp(false)}>Всё понятно <Check size={16}/></button></dialog>
 </MotionConfig>
}
const rootElement=$('root');
const root=rootElement.__reactRoot ??= createRoot(rootElement);
root.render(<App/>);
